### ISSUE TITLE
Long tag name causes RangeDefect at Runtime

### ISSUE THREAD

**Issue by PhilippMDoerner** [treeform/benchy#12]
Just ran into this issue while benching variations of a proc to check whether something improves performance. It appears a hit a character limit of sorts somewhere, which caused a RangeDefect at runtime when printing the table.

Minimal example:

```nim
import benchy


timeIt "truncate_breakfor_memoryalloc long man this is a long tag name":
    let s = "lala"
    keep s
```

This will cause the following error:

`Error: unhandled exception: value out of range: -27 notin 0 .. 9223372036854775807 [RangeDefect]`

It's not a major issue, just a minor inconvenience.
I think the first question that needs to be asked here is whether the current character limit, which is around 35, is desired or not.

If yes, I would advocate for a better error message.

If no, this would count as a bug I assume.

**Comment by PhilippMDoerner** [comment]
I have been informed that @guzba  's PR #11 will take care of the issue (?)
Should it be merged I'll throw up a quick reply whether it fixed it.

**Comment by treeform** [comment]
Hey, thank you for the issue!

I decided to fix this a different way by putting the text on the right side so it can grow as long as it needs to. 

Just update to head for the new version.

Let me know if some thing does not work.
